sshversion: 2
jobs:
  build:
    docker:
      - image: ubuntu:jammy

    steps:
      - run:
          name: install dependencies
          command: |
            apt update
            apt upgrade -y
            apt install -y git python3.10 gawk libgfortran5 python2 python3-pip
            python3.10 -m pip install --user pytest numpy coverage psutil delphi4py pdbmender
      - checkout
      - run:
          name: run tests
          command: |
            set -e
            cd ./tests/
            python3.10 -m pytest test.py